### ISSUE TITLE
The difference in the CPU metrics

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#1]
Hi,
I have tried to use the tool and see the time difference in the CPU metrics which is coming from OS and ABAP server.
![image](https://user-images.githubusercontent.com/68515984/87883688-4cc95200-ca09-11ea-92d6-20ce92641723.png)
Can you please explain how you doing the time belt capturing and why the time difference between AWS CPU and SAP APP servers happened?

**Comment by frumania** [comment]
Hey,
thanks for trying out the solution!
Actually that looks quite consistent. There are 2 factors:
1) There is a small time offset due to the SAP native CPU capturing via 'saposcol', runs usually every 30-60s and our custom monitor, fetches the results through sdf/smon every 60s.
2) saposcol / st06 is applying an average on the raw CPU numbers (capture every 30-60s) - actually i have identified a bug here, which i try to review with SAP,  but for you it seems fine + CloudWatch custom averging (as per config)
